### ISSUE TITLE
San Marino 22 April

### ISSUE THREAD

**Issue by jeffpires** [ec-jrc/COVID-19#2]
22 April, San Marino: CumulativePositive is an outlier and is likely a typo - value should be 476 instead of 4766.  This affects all relevant case total fields in by-country and by-region csv reports.

![Annotation 2020-05-07 095953](https://user-images.githubusercontent.com/5229803/81269428-94b31c80-9049-11ea-96e6-1dac84d7bacd.png)

**Comment by JumbaJookiba** [comment]
Thanks a lot for your check.
We fixed the data in the db according to your suggestion.
The report is generated hourly and will reflect the corrected situation.

Best regards,

Daniele A. GALLIANO
Ingegnere

Da: Jeff<mailto:notifications@github.com>
Inviato: giovedì 7 maggio 2020 10:01
A: ec-jrc/COVID-19<mailto:COVID-19@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [ec-jrc/COVID-19] San Marino 22 April (#2)


22 April, San Marino: CumulativePositive is an outlier and is likely a typo - value should be 476 instead of 4766. This affects all relevant case total fields in by-country and by-region csv reports.

[Annotation 2020-05-07 095953]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5229803%2F81269428-94b31c80-9049-11ea-96e6-1dac84d7bacd.png&data=02%7C01%7C%7Cf0f73a7669ad45aa9d6d08d7f25ce72a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637244353129298862&sdata=rBX3HB0kZ25dhbJQdXXdiRjRrn0pPgQ10Sz6bxvZJEY%3D&reserved=0>

**Comment by jeffpires** [comment]
Thanks for the quick fix!
